### ISSUE TITLE
Don't override custom provider on update

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/orstools-qgis-plugin#108]
#### Here's what I did
I updated the plugin through qgis.

---
#### Here's what I got
my custom providers are gone.

---
#### Here's what I was expecting
my custom providers to be preserved

---
#### Here's what I think could be improved
store custom providers in a different place or in a file that does not get overwritten.

**Comment by SlowMo24** [comment]
also the api-key is lost each time

**Comment by nilsnolde** [comment]
good point. it's the same file, `config.yml`. you got time for a PR? :wink:
