### ISSUE TITLE
Sign Up not working

### ISSUE THREAD

**Issue by FelixKin1993** [GIScience/orstools-qgis-plugin#115]
I can't sign up to get an API Key for the ORS Tools Plugin for Qgis.
I tryed it with Email and with github, and with different browsers, but I only reach https://openrouteservice.org/dev/#/null

**Comment by nilsnolde** [comment]
Please ask questions like that on our forum at https://ask.openrouteservice.org. And outline exactly what you're doing to get to that URL, I can't reproduce.
