### ISSUE TITLE
Removing blue lines in ORS TOOL

### ISSUE THREAD

**Issue by Mikida** [GIScience/orstools-qgis-plugin#120]
#### Here's what I did
Dear someone who can help.

I’m working in QGIS 3.14.16 and using an ORS Tools version 1.2.3. I have encountered a problem with some blue route lines. Even if all layers are unactivated, the blue lines are showing. The lines are a result of using the ORS tool for route planning. I added another line using the ORS tool just to demonstrate (displayed in the picture). There should be some way to remove the line. So, my question is, how can I remove everything or a selection of that what is plotted using the ORS tool?

---
#### Here's what I got

![image_for_ors_question_bluelines](https://user-images.githubusercontent.com/43927151/94550587-a4333c00-025c-11eb-8153-640bf28f524b.PNG)

---
#### Here's what I was expecting

I would want the lines to be removable in an elegant/easy way.

---
#### Here's what I think could be improved
The lines can be removed through restarting QGIS. This cannot however be as intended. The lines should be removable and re-plotted. I don't know how this is done. I have noted other users have had the same problem, but no solution to this problem can be found.

**Comment by davidafuller01** [comment]
+1. Why not remove the blue lines when the waypoints are deleted?

**Comment by Mikida** [comment]
@davidafuller01, this is what I'm trying to do. Does the ORS tool save the waypoints (blue lines), somewhere besides as a new layer? The blue lines cannot be removed simply by removing the calculated route as a layer. If @davidafuller01 has any advice how to remove the blue lines after the waypoint calculation, I would be very happy. Thank you.

**Comment by davidafuller01** [comment]
@Mikida - I was echoing your request that the blue lines be cleared (or a function added to allow the user to clear them). I have the same issue and no solution.

**Comment by fran2a** [comment]
Any update? Thx

**Comment by nilsnolde** [comment]
I'm not a maintainer anymore since a while, but the I'll at least leave the brute force approach here:

```
for a in QgsProject.instance().annotationManager().annotations():
    QgsProject().instance().annotationManager().removeAnnotation(a)
```

in the QGIS Python console. Careful, will remove all the project's annotations. The only way around until someone will fix the issue in the code.

**Comment by FlyingEagle** [comment]
The Python Code above is not working for me or I make mistakes, I am a python noob ;-)

Are there any updates for this issue?

**Comment by koebi** [comment]
Hey,

no you are probably not, is is very well possible that the code above does not work in certain situations.
This is currently being worked on, albeit somewhat irratically, so there's no expected timeframe for when this will get fixed.

**Comment by ThePieMonster** [comment]
I am also experiencing the blue lines not being removed once a new route layer is created. Even after removing the created layer or exiting out of the plugin, the blue lines remain. Very annoying!

**Comment by Merydian** [comment]
Is it possible that this isn't a problem anymore? I only see blue lines during digitization of the route points. They dissappear completely after ending the digitization.

**Comment by TheGreatRefrigerator** [comment]
Might be OS and QGIS version specific, as long as not thoroughly tested on different versions, i would leave this open.
