### ISSUE TITLE
Add option to set timeout when creating a provider

### ISSUE THREAD

**Issue by rabidllama** [GIScience/orstools-qgis-plugin#122]
#### Here's what I did

Often people use a local instance of openrouteservice for complex requests that exceed the limits of the standard openrouteservice API (e.g. large matrix requests). When such requests are made it is often the case that they can take some time to complete. 

---
#### Here's what I got

After some default time, an exception is returned that there was a timeout.

---
#### Here's what I was expecting

When running a self hosted instance, the timeout should be longer to accomadate the longer duration needed for complex processes 

---
#### Here's what I think could be improved
It would be good to be able to specify an override to the default timeout value when users make use of a local install. This could be set in the configuration area when the custom location is setup or edited

**Comment by jannefleischer** [comment]
I already implemented that a couple of weeks ago. Just waiting for a merge. https://github.com/GIScience/orstools-qgis-plugin/pull/121 - until than you can install from my branch manually.
