### ISSUE TITLE
Allow "round journey" for optimisaiton

### ISSUE THREAD

**Issue by rabidllama** [GIScience/orstools-qgis-plugin#125]
When using advanced routing options and selecting the travelling salesperson optimisation, it would be useful to be able to indicate that the generated route should start and end at the same location rather than having to duplicate the starting point as a designated end point.

**Comment by koebi** [comment]
In the same overhaul, the _Optimize Start_ and _Optimize End_ options should be renamed to _Fix End_ and _Fix Start_ to clarify their meaning.
