### ISSUE TITLE
Could not find point within a radius of 350.0 meters

### ISSUE THREAD

**Issue by d3netxer** [GIScience/orstools-qgis-plugin#128]
#### Here's what I did
I ran Directions From Points from 1 layer

---
#### Here's what I got
error message:
```
Feature ID caused a ApiError:
404 ({"error":{"code":2010,"message":"Could not find point 10: -112.6955790 41.4618090 within a radius of 350.0 meters."},"info":{"engine":{"version":"6.3.6","build_date":"2021-03-02T18:34:49Z"},"timestamp":1615305477777}})
```

---
#### Here's what I was expecting
-The point (point 10 does not correspond to the ID field, I think that it would be an improvement if it did)
-I do not know why there is an error. In OpenStreetMap, I do not see any private roads nearby. This was a possible reason of the error reading this issue (https://ask.openrouteservice.org/t/code-2010-could-not-find-point-0-70-7386400-29-2564500-within-a-radius-of-350-0-meters/2351). Even when I delete the point I found by zooming into the list coordinates and run the process again, it lists another point with the same error. This makes it difficult to find where the error is. I had to delete many points until the process finally ran without an error.

---
#### Here's what I think could be improved
-I am not sure how the error can be fixed, as I have not found out why the error is occurring.

**Comment by d3netxer** [comment]
I found out why the error occurs. There is not a road within 350m of the point. Could the error message be changed to reflect this?

**Comment by koebi** [comment]
Hey,
this is not an error message of the plugin, but the response and thus error message of the ORS API.
I agree, that it's not the clearest error message in the world.
I have [opened an issue in the backend](https://github.com/GIScience/openrouteservice/issues/922) regarding your suggestion on changing the error message, and will keep track over there.
