### ISSUE TITLE
Clarify meaning of `Layer ID Field`

### ISSUE THREAD

**Issue by koebi** [GIScience/orstools-qgis-plugin#143]
There seems to be [a bit](https://github.com/GIScience/orstools-qgis-plugin/issues/130) of [confusion](https://ask.openrouteservice.org/t/start-and-end-point-of-route-points-1-layer/1763) about the usage of the `Layer ID Field`.
It seems that most people assume this to be the field that is used for determining the order of waypoints when requesting a route.

This will get fixed by #142, but the intended usage should still be communicated more clearly (as I am also unsure on what the idea is and how it should get used).

**Comment by koebi** [comment]
The idea of this parameter is, that one attribute of the input layer is kept in the output layer to be able to join the input layer's attributes to the output layer.

Here's an example question for this feature from our support:
> When I use openrouteservices to calculate the accessibility of a certain point, I get isochrones back, which unfortunately dont have the original attributes of the point-Layer. Is there any possibility to have the isochrones display the original attributes?

The idea that this is used to *join* attribute tables may be reflected in the parameter name. Suggestions are welcome.

**Comment by Merydian** [comment]
Why not simply `Join-ID Field`?

**Comment by koebi** [comment]
I am not sure if that is the only purpose of the fileld, but that's probably already better than what we have.
Maybe @maze2point0 has a suggestion?
