### ISSUE TITLE
Refactor _Advanced Directions_

### ISSUE THREAD

**Issue by koebi** [GIScience/orstools-qgis-plugin#144]
- [x] fix blue lines (#120)
- [x] don't remove vertex markers once route is generated
- [x] add option to export list to layer
- [x] make waypoints re-orderable
- [x] make waypoints drag-and-droppable
- [ ] #211

**Comment by Merydian** [comment]
For the export of the vertices i'd suggest something like this:
<img width="366" alt="image" src="https://github.com/GIScience/orstools-qgis-plugin/assets/81414045/fe641b1d-269e-4827-992b-7da108e687c2">

**Comment by Merydian** [comment]
Is `don't remove vertex markers once route is generated` really necessary, when there an option to save the vertices as a layer?

**Comment by koebi** [comment]
Maybe we could add a hint above the `choose export path` that notes that the markers will vanish if not saved?

**Comment by koebi** [comment]
I've converted the one idea that was in here to a separate issue (#211) and will see this as complete :)
