### ISSUE TITLE
Add styling from `.qml`-file

### ISSUE THREAD

**Issue by koebi** [GIScience/orstools-qgis-plugin#149]
Generated routes/lines being rather invisible is a bother.
Using `postProcessAlgorithm()` as described [here](https://gis.stackexchange.com/questions/317450/qgis-3-4-how-to-add-qml-style-to-sink-in-processing), we could load a `.qml`-file to style any output layers.

That would enable us to

1. easily style any layer using the builtin qgis tools, then exporting .qml
2. iterate this process for any neccessary changes
3. apply the same style multiple times without repeating code

**Comment by MichaelsJP** [comment]
good resource to find the most suitable colour ramps: https://github.com/GIScience/ors-map-client/pull/298
