### ISSUE TITLE
Add keyboard shortcut

### ISSUE THREAD

**Issue by koebi** [GIScience/orstools-qgis-plugin#150]
We could think about adding a shortcut for the ORS-Plugin - something like the F-keys or `CTRL-F?` sounds rather non-intrusive and would make the plugin more keyboard-friendly :)

As an example for implementation, look at [the plugin reloader](https://github.com/borysiasty/plugin_reloader/blob/861e87ce072e9f80c4f1b6d061370d6bbb7ff19d/reloader_plugin.py#L135) that sets `CTRL-F5` as their shortcut.

**Comment by koebi** [comment]
[This list](https://docs.qgis.org/3.16/en/docs/user_manual/introduction/qgis_gui.html) has the keyboard shortcuts listed.
A non-used one that "makes sense" would be `CTRL + R`, mnemonic "route" or "control route" or sth. like that. `CTRL + F` is unfortunately already taken…

**Comment by TheGreatRefrigerator** [comment]
sounds ok.
is there a notice if the same shortcut is assigned to multiple actions? (e.g. QGIS introducing a native CTRL+R in the future?)
