### ISSUE TITLE
Error message when using Matrix batch tool

### ISSUE THREAD

**Issue by sigsdis30** [GIScience/orstools-qgis-plugin#164]
QGIS 3.16.14
ORS Tools 1.5.0
Batch Jobs > Matrix
Provider: openrouteservice with a valid API token
Travel mode: driving car
Input start: a point layer (31 points)
Start ID: unique code
Input end: the same point layer
Start ID: the same unique code
Matrix: temporary layer

---
#### Here's what I got
Traceback (most recent call last):
File "/.../QGIS/QGIS3/profiles/default/python/plugins/ORStools/proc/matrix_proc.py", line 91, in processAlgorithm
options = self.parseOptions(parameters, context)
File "/.../QGIS/QGIS3/profiles/default/python/plugins/ORStools/proc/base_processing_algorithm.py", line 195, in parseOptions
features_raw = parameters[self.IN_AVOID_FEATS]
KeyError: 'INPUT_AVOID_FEATURES'
---

I successfully used this tool in the last months. My software hadn't been updated. I tried to update ORS Tools

**Comment by TheGreatRefrigerator** [comment]
Also see https://ask.openrouteservice.org/t/qgis-ors-tools-matrix-from-layers-keyerror/3461/2

**Comment by sigsdis30** [comment]
It works fine with version 1.4.0
I specify that my layer is a PostGIS table.
Thank you
