### ISSUE TITLE
cycling-road not working

### ISSUE THREAD

**Issue by m-kuhn** [GIScience/orstools-qgis-plugin#167]
results in a 404
I didn't find a list of supported "profiles" in the API docs https://openrouteservice.org/dev/#/api-docs/directions

Using cycling-regular for now

**Comment by TheGreatRefrigerator** [comment]
Hi @m-kuhn,

just tested for `cycling-road` and didn't encounter a problem.
The profile is a path parameter (part of the URL) you need to set it in a separate Tab in the API Playground.

If :
1. you are not using a local ORS instance and didn't build the cycling-road profile
2. the cycling-road profile [is not down](http://status.openrouteservice.org)

there shouldn't be a problem.

Could you maybe go into more detail about what you have done and what's not working?

**Comment by m-kuhn** [comment]
I was using the processing alg "Directions from polyline" on a line layer and got a 404. Retrying with `cycling-regular` worked fine on the same data just after.
However, retrying now, I cannot reproduce. Either there was a temporary issue with the service or I did something bad.
Sorry for the noise.
