### ISSUE TITLE
Isochrone center cannot be set as "destination"

### ISSUE THREAD

**Issue by pcopissa** [GIScience/orstools-qgis-plugin#171]
According to ORS isochropne API (https://openrouteservice.org/dev/#/api-docs/v2/isochrones/{profile}/post) it is possible to use the optional field `location_type` to specify that the points in the `locations` field are destinations (that is, the output isochrone is the set of points **from which** we can reach the location in less than X minutes or meters). However the default is `start` (that is, the output is the set of points reachable in less than X minutes, starting from the location). There is no GUI widget (or any other way ?) to specify that the locations should be destinations.

Expectation is that there should be a way to specify which type of location is desired.

**Comment by koebi** [comment]
Hey,

yes, the QGIS plugin is unfortunately not feature complete in regard to the API, and it is not something we're currently working on.
We'll happily review a pull request implementing this, though :)

Best regards
