### ISSUE TITLE
Isochrone coarseness/smoothness cannot be set

### ISSUE THREAD

**Issue by pcopissa** [GIScience/orstools-qgis-plugin#172]
According to ORS isochropne API (https://openrouteservice.org/dev/#/api-docs/v2/isochrones/{profile}/post) it is possible to use the optional field `smoothing` to specify the coarseness of the isochrone (in terms of how short a segment of the output polygon can be). It looks like that the default is `25`. There is no GUI widget (or any other way ?) to specify the coarseness of the isochrones.

Expectation is that there should be a way to specify how coarse the isochrones should be.

**Comment by koebi** [comment]
fixed in #176 and the corresponding #199
