### ISSUE TITLE
Network error while running matrix from layers with local server

### ISSUE THREAD

**Issue by yungNeiko** [GIScience/orstools-qgis-plugin#175]
#### Here's what I did
Hi,
I followed the SyntaxByte video tutorial, and now I have the ORS services available through Docker. Everything worked fine with a small own dataset (only using and needing the Matrix from Layers Tool). Now I wanted to use it on some bigger data for work, and now I get this error. I tried to solve this problem on my own. So I increased the maximum_routes a little bit higher than I need and increased the RAM to -Xms2g -Xmx4g, but nothing worked. I also checked my provider settings multiple times to be sure that the localhost base-url is 8080. 

Thanks a lot in advance.

---
#### Here's what I got
![Problem](https://user-images.githubusercontent.com/119658803/205251226-2af61451-ce70-4a1a-b5e5-f0565dbdab61.PNG)

**Comment by yungNeiko** [comment]
I got it working for me. In the provider settings I increased the "request timeout in seconds" to the maximum at 3600.

**Comment by koebi** [comment]
Hey,
great that you got it working :))
Best regards
