### ISSUE TITLE
Mention omission of configuration options when using Traveling Salesman

### ISSUE THREAD

**Issue by koebi** [GIScience/orstools-qgis-plugin#190]
There is a note in the main GUI.
Something similar should be added to the processing plugin.

**Comment by Merydian** [comment]
In the german help the name "Rundreise-Optimierung" (Due to the linked Wikipedia article) is used, while in the parameter selection it is called "Wegpunktoptimierung". Which one should be used in the comment on the omission of advanced config options?

**Comment by koebi** [comment]
I'd keep the comment as is and just add to it?
As given, you can fix a start point, end point or both, so you're optimizing waypoints, not necessarily a round trip?

**Comment by Merydian** [comment]
Alright, then i guess we should replace "Rundreise-Optimierung" with "Wegpunktoptimierung"? Would probably clear up some potential confusion and as i see it "Rundreise-Optimierung" dosen't even reference the name of the linked article.
