### ISSUE TITLE
Mention shortcut in changelog or settle on auto-generating changelog

### ISSUE THREAD

**Issue by koebi** [GIScience/orstools-qgis-plugin#194]

**Comment by Merydian** [comment]
keepachangelog.com states that: 

> Using commit log diffs as changelogs is a bad idea: they're full of noise. Things like merge commits, commits with obscure titles, documentation changes, etc.

Which means we should stick to manual logging? I suppose its better since we have to think of a good simple description about what has changed.

**Comment by koebi** [comment]
I'd agree, let's do that!
