### ISSUE TITLE
investigate whether importing the GUI point list is viable

### ISSUE THREAD

**Issue by koebi** [GIScience/orstools-qgis-plugin#211]

**Comment by koebi** [comment]
We could think about :
* populating the GUI point list from a layer
* populating the list via GeoJSON (compare Valhalla)

**Comment by Merydian** [comment]
Isn't that what the processing algorithms are for? Maybe keeping it the way it is can be a good motivation to try them out?

**Comment by koebi** [comment]
Huh, good point :)
Maybe that's something we can mention in docs/wiki somewhere?

**Comment by koebi** [comment]
https://ask.openrouteservice.org/t/how-to-input-a-layer-in-routing-gui/5657/2 just came up regarding this :D

I do agree, a tooltip sounds quite good :+1:
