### ISSUE TITLE
`<str>.removesuffix()` only available in Python3.9

### ISSUE THREAD

**Issue by koebi** [GIScience/orstools-qgis-plugin#215]
This comes from
https://ask.openrouteservice.org/t/how-to-fix-this-provider-error-problem/5649/2

`<str>.removesuffix()` and `<str>.removeprefix()` are only available in Python 3.9.

I don't know which QGIS version this corresponds to - we should find that out and decide whether we want to refactor until QGIS broadly supports 3.9 or whether we keep and set a higher min version.

**Comment by Merydian** [comment]
If the backwards compatibility is only dependent on this line why not change it to support older versions? Doesn't seem like a lot of work to me. Is there anything else problematic with newer versions?

If this only allows the Plugin to run with Python 3.9 we should probably fix this quickly, right?
