### ISSUE TITLE
QGIS -  Rename of Isochrones from layer tool breaking code

### ISSUE THREAD

**Issue by davidlgalt** [GIScience/orstools-qgis-plugin#232]
Two things:

Number 1 - renaming means I need to go in and change all my code
Number 2 - the new name which generates the variable: Isochrones_from_Point-Layer breaks the code as QGIS models won't process variables with hyphens and sees the variable as Layer_from_Point, excluding the part before the hyphen.

**Comment by merydian** [comment]
Hi @davidlgalt,

we'd need a little more information on this. Could you provide us with the a model you're having issues with? Then we can have a closer look. Some info on your setup may also be of help: OS, QGis Version, plugin version etc. 

Best regards
