### ISSUE TITLE
Isochrones with seconds

### ISSUE THREAD

**Issue by tobiw1978** [GIScience/orstools-qgis-plugin#237]
Hi there.
is it possible to calculate isochrones in QGIS with the ORS (Openrouteservice) Plugin in minutes and seconds. I just can calculate full minutes. On the Webservice you can calculate the seconds with decimal minutes.

**Comment by merydian** [comment]
Hi, 
thanks for your question. As of now this is not possible, we can include it in the next release. 

Best regards
