### ISSUE TITLE
feature request: for Traveling Salesman Problem, return stop order

### ISSUE THREAD

**Issue by d3netxer** [GIScience/orstools-qgis-plugin#244]
#### Here's what I did
Ran Traveling Salesman Problem

---
#### Here's what I got
A line shapefile of the result. However, I do not know the order of the stops

---
#### Here's what I was expecting
somehow to be presented the order of the stops

---
#### Here's what I think could be improved
I tested using the ORS API Playground. I had three stops in the input, and it returns only one route. This is fine. For the single route there is a steps property that lists the steps. If this information could be accessed and presented in the QGIS plug-in I think it would be an improvement

**Comment by merydian** [comment]
Hi, there is a pending pull request for this ( #227 ). So this will be included in the next release. If you'd like to have this feature earlier you can checkout the feature branch and install the plugin from there. There is instructions on how to install is in the Readme.md. 

Best regards

**Comment by d3netxer** [comment]
ok thank you!
