### ISSUE TITLE
NaN issue

### ISSUE THREAD

**Issue by Geremia** [GIScience/orstools-qgis-plugin#270]
I'm getting:

<details><summary>Details</summary>
<p>

```
Traceback (most recent call last):
File "/home/geremia/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ORStools/common/client.py", line 167, in request
response, content = self.nam.request(
^^^^^^^^^^^^^^^^^
File "/home/geremia/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ORStools/common/networkaccessmanager.py", line 278, in request
raise self.http_call_result.exception
ORStools.common.networkaccessmanager.RequestsException: Network error #400: Error transferring https://api.openrouteservice.org/optimization? - server replied: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/geremia/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ORStools/common/client.py", line 175, in request
self._check_status()
File "/home/geremia/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ORStools/common/client.py", line 237, in _check_status
raise exceptions.ApiError(str(status_code), message)
ORStools.utils.exceptions.ApiError: 400 ({"code":2,"error":"Invalid JSON object in request, please add vehicles and jobs or shipments to the object body"})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/geremia/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ORStools/proc/directions_points_layer_proc.py", line 222, in processAlgorithm
response = ors_client.request("/optimization", {}, post_json=params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/geremia/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ORStools/common/client.py", line 187, in request
f"Feature ID {post_json['id']} caused a {e.__class__.__name__}: {str(e)}", 2
~~~~~~~~~^^^^^^
KeyError: 'id'

Execution failed after 0.95 secondi
```

</p>
</details> 

Looking at the ORS Tools log, I see that NaNs are in one of the locations:

`2024-07-24T14:25:02     INFO    url: https://api.openrouteservice.org/optimization?`:
```json
             Parameters: {
              "jobs": [
              {
              "location": [
              -78.165341,
              38.904633
              ],
              "id": 0
              },
              {
              "location": [
              -78.167594,
              38.910562
              ],
              "id": 1
              },
              {
              "location": [
              NaN,
              NaN
              ],
              "id": 2
              },
              {
              "location": [
              -78.166773,
              38.927105
              ],
              "id": 3
              },
[…]
```

Viewing that location in the vertex editor, I see it does not have NaN `x` and `y`.

I'm also getting that the Start and/or End points contain NaNs, depending on "Round Trip", "Fix Start Point", etc.

For some reason, I can get the request to have no NaNs if I exclude points with IDs > 3 and choose "Fix End Point".

QGIS 3.38.0 and ORS Tools 1.8.3 on Linux

**Comment by Geremia** [comment]
I noticed that choosing "Fixed Start & End Point" was the only way I could get it to work.

**Comment by Geremia** [comment]
There were a couple issues here, one of which was that I was trying to optimize 53 points, and there's a [50 points restriction](https://openrouteservice.org/restrictions/#tablepress-8-name).

ORS Tools should give a more user-friendly error message when the points are >50.

NaN,NaN locations should also be dropped or prompt an error message.

**Comment by Geremia** [comment]
Actually, the issue still persists, even with 40 points…

**Comment by merydian** [comment]
Hi, firstly thanks for your contribution here. 

It looks like there might be something wrong with the input. See:

> ORStools.utils.exceptions.ApiError: 400 ({"code":2,"error":"Invalid JSON object in request, please add vehicles and jobs or shipments to the object 

It's hard to tell whether this is fixable on your side, at least without some more info on your input data. It would be best if you are able to provide us with a reproducible minimal dataset and config JSON. The latter you can export from the `Directions from Points-Layer` tool directly. Just click `Advanced` on the bottom, then `Copy as JSON` and paste here. For the layer any export will do, just attach it here in your comment.

Your point on the NaN values is still valid, but only a minor issue with error handling. We'll see to this as well. 

Many thanks in advance.

**Comment by Geremia** [comment]
@merydian 

> It would be best if you are able to provide us with a reproducible minimal dataset and config JSON. The latter you can export from the `Directions from Points-Layer` tool directly. Just click `Advanced` on the bottom, then `Copy as JSON` and paste here.

```json
{
  "area_units": "m2",
  "distance_units": "meters",
  "ellipsoid": "EPSG:7030",
  "inputs": {
    "CSV_COLUMN": "",
    "CSV_FACTOR": null,
    "EXPORT_ORDER": false,
    "EXTRA_INFO": [],
    "INPUT_AVOID_BORDERS": null,
    "INPUT_AVOID_COUNTRIES": "",
    "INPUT_AVOID_FEATURES": [],
    "INPUT_AVOID_POLYGONS": null,
    "INPUT_LAYER_FIELD": "fid",
    "INPUT_OPTIMIZE": 0,
    "INPUT_POINT_LAYER": "/home/geremia/geocoded.gpkg",
    "INPUT_PREFERENCE": 1,
    "INPUT_PROFILE": 0,
    "INPUT_PROVIDER": 0,
    "INPUT_SORTBY": "fid",
    "OUTPUT": "/home/geremia/route.gpkg"
  }
}
```

> For the layer any export will do, just attach it here in your comment.

[geocoded.tar.gz](https://github.com/user-attachments/files/16419547/geocoded.tar.gz)

**Comment by merydian** [comment]
This is throwing a different error now than the one you outlined above: 
`ORStools.utils.exceptions.ApiError: 400 ({"code":2,"error":"Duplicate job id: 15."})`

This is due to a duplicate in the data -- the features with `fid` 17 and 19 are the same which causes the error. You can check this using the `Topology Checker` in the plugins manager.

**Comment by Geremia** [comment]
@merydian Interesting.
`Topology Checker` didn't find any errors, though.
I removed `fid` 19 and ran into another issue:
```
Traceback (most recent call last):
File "/home/alan/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ORStools/proc/directions_points_layer_proc.py", line 221, in processAlgorithm
params = get_params_optimize(points, profile, optimization_mode)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/geremia/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ORStools/utils/processing.py", line 57, in get_params_optimize
start = end = point_list.pop(0)
^^^^^^^^^^^^^^^^^
IndexError: pop from empty list

Execution failed after 0.06 secondi

Caricamento layer
Algoritmo 'Directions from 1 Point-Layer' terminato
```

**Comment by merydian** [comment]
How did you remove the point? If I take your `geocoded` layer and remove the feature with `fid 19` and use your config JSON from above, everything runs through.

How did you use the Topology checker?

**Comment by Geremia** [comment]
@merydian  
> How did you remove the point?

Deleted the row in the attribute table. Maybe that just removed the attributes and not the point?
> How did you use the Topology checker?

I clicked the verify all ✅ button.

**Comment by Geremia** [comment]
@merydian 

Oh I see I had to add a rule to detect duplicates before pressing the ✅ button.

I deleted the vertex instead, and it worked.

Still, ORS Tools should check first or offer a better warning about what the issue is.
